name: netwscan
description: Local Network Search Tool
version: 1.0.0-beta

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: "0.5.12"

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - lib/language.json
    - Icons/main.png
    - Icons/netwscanIcon.ico

